version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8095:8095"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - .env
